var fs = require('fs');
var path = 'C:/Users/FH01/.qclaw/workspace-cwapojim0yfmyvq8/Travel-Lab/_fix_pdf_garble.py';

var lines = [];
function L(s) { lines.push(s); }

L('# -*- coding: utf-8 -*-');
L('import sys; sys.stdout.reconfigure(encoding="utf-8")');
L('from reportlab.pdfbase import pdfmetrics');
L('from reportlab.pdfbase.ttfonts import TTFont');
L('from reportlab.lib.pagesizes import A4');
L('from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak');
L('from reportlab.lib import colors');
L('from reportlab.lib.styles import ParagraphStyle');
L('from reportlab.lib.units import mm');
L('from reportlab.lib.enums import TA_CENTER');
L('import os');
L('');
L('pdfmetrics.registerFont(TTFont("MSJH", "C:/Windows/Fonts/msjh.ttc", subfontIndex=0))');
L('pdfmetrics.registerFont(TTFont("MSJHB", "C:/Windows/Fonts/msjh.ttc", subfontIndex=1))');
L('');
L('TEAL = colors.HexColor("#0ABAB5")');
L('DARK = colors.HexColor("#1a1a2e")');
L('LIGHT_BG = colors.HexColor("#e8f8f7")');
L('');
L('h1 = ParagraphStyle("H1", fontName="MSJHB", fontSize=18, leading=24, textColor=DARK, spaceAfter=12, alignment=TA_CENTER)');
L('h2 = ParagraphStyle("H2", fontName="MSJHB", fontSize=14, leading=20, textColor=TEAL, spaceBefore=16, spaceAfter=8)');
L('h3 = ParagraphStyle("H3", fontName="MSJHB", fontSize=11, leading=16, textColor=DARK, spaceBefore=10, spaceAfter=6)');
L('body = ParagraphStyle("Body", fontName="MSJH", fontSize=9.5, leading=15, textColor=colors.HexColor("#333333"), spaceAfter=6)');
L('tip = ParagraphStyle("Tip", fontName="MSJH", fontSize=9, leading=14, textColor=colors.HexColor("#d35400"), leftIndent=15, spaceAfter=4)');
L('center = ParagraphStyle("Center", fontName="MSJH", fontSize=9, leading=14, alignment=TA_CENTER)');
L('small_center = ParagraphStyle("SC", fontName="MSJH", fontSize=8, leading=12, textColor=colors.HexColor("#888888"), alignment=TA_CENTER)');
L('');
L('def tbl(headers, rows, widths):');
L('    d = [[Paragraph("<b>"+h+"</b>", body) for h in headers]]');
L('    for r in rows: d.append([Paragraph(str(c), body) for c in r])');
L('    t = Table(d, colWidths=widths)');
L('    t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),TEAL),("TEXTCOLOR",(0,0),(-1,0),colors.white),("ALIGN",(0,0),(-1,-1),"CENTER"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("FONTNAME",(0,0),(-1,-1),"MSJH"),("FONTSIZE",(0,0),(-1,-1),8),("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#cccccc")),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,LIGHT_BG]),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]))');
L('    return t');
L('');
L('def cta(story):');
L('    story.append(Spacer(1,20))');
L('    bd = [[Paragraph("<b>[ \u66f4\u591a\u5b8c\u6574\u653b\u7565 ]</b>", center)], [Paragraph("golightly.fun \u2014 \u5746\u5728\u8def\u4e0a\u7684\u65c5\u904a\u5be6\u9a57\u5ba4", center)], [Paragraph("<b>[ \u5373\u6642\u65c5\u904a\u8aee\u8a62 ]</b>", center)], [Paragraph("\u52a0\u5165 LINE \u7fa4\u7d44\uff0c\u514d\u8cbb\u7372\u5f97\u884c\u7a0b\u5efa\u8b70", center)]]');
L('    b = Table(bd,[380])');
L('    b.setStyle(TableStyle([("BOX",(0,0),(-1,-1),2,TEAL),("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#f0fffe")),("ALIGN",(0,0),(-1,-1),"CENTER"),("TOPPADDING",(0,0),(-1,-1),10),("BOTTOMPADDING",(0,0),(-1,-1),10)]))');
L('    story.append(b); story.append(Spacer(1,15))');
L('    story.append(Paragraph("\u5746\u5728\u8def\u4e0a Travel Lab \u00a9 2026 | golightly.fun", small_center))');
L('    story.append(Paragraph("\u50f9\u683c\u8207\u8cc7\u8a0a\u53ef\u80fd\u96a8\u6642\u8b8a\u52d5\uff0c\u51fa\u767c\u524d\u8acb\u518d\u6b21\u78ba\u8a8d", small_center))');
L('');
L('def build(fn, title, sub, secs):');
L('    p = "downloads/" + fn + ".pdf"');
L('    doc = SimpleDocTemplate(p, pagesize=A4, leftMargin=25*mm, rightMargin=25*mm, topMargin=20*mm, bottomMargin=20*mm)');
L('    s = []; s.append(Paragraph(title,h1)); s.append(Paragraph(sub,center)); s.append(Spacer(1,8))');
L('    for sec in secs: sec(s)');
L('    cta(s); doc.build(s); return os.path.getsize(p)');
L('');
L('OK = "[OK] "  # safe marker - no unicode symbols');
L('WRN = "[!] "  # warning marker');
L('STAR = "* "   # bullet');
L('PLN = "> "    # tip arrow');
L('CROSS = "X "  # cross/don\'t');
L('');

fs.writeFileSync(path, lines.join('\n'), 'utf-8');
console.log('Header OK: ' + lines.length + ' lines');
